/**
 * Every choice on the Discord application, exactly as the live page offered it.
 *
 * SOURCE  https://job-boards.greenhouse.io/discord/jobs/8571766002
 *         Harvested headlessly on 2026-09-23 by opening each picker, and by typing each search
 *         below into the two pickers that search as you type.
 *
 * The two searchable pickers call Greenhouse's servers, which a copy cannot. So what they return
 * here is what the live page returned for the searches recorded below; anything else typed is
 * matched against every result recorded. Nothing was added, renamed or reordered.
 */

/** The phone number's country picker: 244 entries, each with its dialling code. */
export const PHONE_COUNTRIES: string[] = [
  "United States +1",
  "Afghanistan +93",
  "Åland Islands +358",
  "Albania +355",
  "Algeria +213",
  "American Samoa +1",
  "Andorra +376",
  "Angola +244",
  "Anguilla +1",
  "Antigua & Barbuda +1",
  "Argentina +54",
  "Armenia +374",
  "Aruba +297",
  "Ascension Island +247",
  "Australia +61",
  "Austria +43",
  "Azerbaijan +994",
  "Bahamas +1",
  "Bahrain +973",
  "Bangladesh +880",
  "Barbados +1",
  "Belarus +375",
  "Belgium +32",
  "Belize +501",
  "Benin +229",
  "Bermuda +1",
  "Bhutan +975",
  "Bolivia +591",
  "Bosnia & Herzegovina +387",
  "Botswana +267",
  "Brazil +55",
  "British Indian Ocean Territory +246",
  "British Virgin Islands +1",
  "Brunei +673",
  "Bulgaria +359",
  "Burkina Faso +226",
  "Burundi +257",
  "Cambodia +855",
  "Cameroon +237",
  "Canada +1",
  "Cape Verde +238",
  "Caribbean Netherlands +599",
  "Cayman Islands +1",
  "Central African Republic +236",
  "Chad +235",
  "Chile +56",
  "China +86",
  "Christmas Island +61",
  "Cocos (Keeling) Islands +61",
  "Colombia +57",
  "Comoros +269",
  "Congo - Brazzaville +242",
  "Congo - Kinshasa +243",
  "Cook Islands +682",
  "Costa Rica +506",
  "Côte d’Ivoire +225",
  "Croatia +385",
  "Cuba +53",
  "Curaçao +599",
  "Cyprus +357",
  "Czechia +420",
  "Denmark +45",
  "Djibouti +253",
  "Dominica +1",
  "Dominican Republic +1",
  "Ecuador +593",
  "Egypt +20",
  "El Salvador +503",
  "Equatorial Guinea +240",
  "Eritrea +291",
  "Estonia +372",
  "Eswatini +268",
  "Ethiopia +251",
  "Falkland Islands +500",
  "Faroe Islands +298",
  "Fiji +679",
  "Finland +358",
  "France +33",
  "French Guiana +594",
  "French Polynesia +689",
  "Gabon +241",
  "Gambia +220",
  "Georgia +995",
  "Germany +49",
  "Ghana +233",
  "Gibraltar +350",
  "Greece +30",
  "Greenland +299",
  "Grenada +1",
  "Guadeloupe +590",
  "Guam +1",
  "Guatemala +502",
  "Guernsey +44",
  "Guinea +224",
  "Guinea-Bissau +245",
  "Guyana +592",
  "Haiti +509",
  "Honduras +504",
  "Hong Kong SAR China +852",
  "Hungary +36",
  "Iceland +354",
  "India +91",
  "Indonesia +62",
  "Iran +98",
  "Iraq +964",
  "Ireland +353",
  "Isle of Man +44",
  "Israel +972",
  "Italy +39",
  "Jamaica +1",
  "Japan +81",
  "Jersey +44",
  "Jordan +962",
  "Kazakhstan +7",
  "Kenya +254",
  "Kiribati +686",
  "Kosovo +383",
  "Kuwait +965",
  "Kyrgyzstan +996",
  "Laos +856",
  "Latvia +371",
  "Lebanon +961",
  "Lesotho +266",
  "Liberia +231",
  "Libya +218",
  "Liechtenstein +423",
  "Lithuania +370",
  "Luxembourg +352",
  "Macao SAR China +853",
  "Madagascar +261",
  "Malawi +265",
  "Malaysia +60",
  "Maldives +960",
  "Mali +223",
  "Malta +356",
  "Marshall Islands +692",
  "Martinique +596",
  "Mauritania +222",
  "Mauritius +230",
  "Mayotte +262",
  "Mexico +52",
  "Micronesia +691",
  "Moldova +373",
  "Monaco +377",
  "Mongolia +976",
  "Montenegro +382",
  "Montserrat +1",
  "Morocco +212",
  "Mozambique +258",
  "Myanmar (Burma) +95",
  "Namibia +264",
  "Nauru +674",
  "Nepal +977",
  "Netherlands +31",
  "New Caledonia +687",
  "New Zealand +64",
  "Nicaragua +505",
  "Niger +227",
  "Nigeria +234",
  "Niue +683",
  "Norfolk Island +672",
  "North Korea +850",
  "North Macedonia +389",
  "Northern Mariana Islands +1",
  "Norway +47",
  "Oman +968",
  "Pakistan +92",
  "Palau +680",
  "Palestinian Territories +970",
  "Panama +507",
  "Papua New Guinea +675",
  "Paraguay +595",
  "Peru +51",
  "Philippines +63",
  "Poland +48",
  "Portugal +351",
  "Puerto Rico +1",
  "Qatar +974",
  "Réunion +262",
  "Romania +40",
  "Russia +7",
  "Rwanda +250",
  "Samoa +685",
  "San Marino +378",
  "São Tomé & Príncipe +239",
  "Saudi Arabia +966",
  "Senegal +221",
  "Serbia +381",
  "Seychelles +248",
  "Sierra Leone +232",
  "Singapore +65",
  "Sint Maarten +1",
  "Slovakia +421",
  "Slovenia +386",
  "Solomon Islands +677",
  "Somalia +252",
  "South Africa +27",
  "South Korea +82",
  "South Sudan +211",
  "Spain +34",
  "Sri Lanka +94",
  "St. Barthélemy +590",
  "St. Helena +290",
  "St. Kitts & Nevis +1",
  "St. Lucia +1",
  "St. Martin +590",
  "St. Pierre & Miquelon +508",
  "St. Vincent & Grenadines +1",
  "Sudan +249",
  "Suriname +597",
  "Svalbard & Jan Mayen +47",
  "Sweden +46",
  "Switzerland +41",
  "Syria +963",
  "Taiwan +886",
  "Tajikistan +992",
  "Tanzania +255",
  "Thailand +66",
  "Timor-Leste +670",
  "Togo +228",
  "Tokelau +690",
  "Tonga +676",
  "Trinidad & Tobago +1",
  "Tunisia +216",
  "Turkey +90",
  "Turkmenistan +993",
  "Turks & Caicos Islands +1",
  "Tuvalu +688",
  "U.S. Virgin Islands +1",
  "Uganda +256",
  "Ukraine +380",
  "United Arab Emirates +971",
  "United Kingdom +44",
  "Uruguay +598",
  "Uzbekistan +998",
  "Vanuatu +678",
  "Vatican City +39",
  "Venezuela +58",
  "Vietnam +84",
  "Wallis & Futuna +681",
  "Western Sahara +212",
  "Yemen +967",
  "Zambia +260",
  "Zimbabwe +263"
];

/** What the School picker shows the moment it opens: the first hundred, alphabetically. */
export const SCHOOLS_ON_OPEN: string[] = [
  "Aalborg University",
  "Aalto University",
  "Aarhus University",
  "Abertay University",
  "Aberystwyth University",
  "Abilene Christian University",
  "Abo Akademi University",
  "Abraham Baldwin Agricultural College",
  "Abu Dhabi University",
  "Academy of Art University",
  "Acadia University",
  "Acharya Nagarjuna University",
  "Acupuncture and Integrative Medicine College - Berkeley",
  "Adams State University",
  "Adelphi University",
  "Adrian College",
  "Adventist University of Health Sciences",
  "Agnes Scott College",
  "AIB College of Business",
  "Ain Shams University",
  "Airlangga University",
  "Ajou University",
  "Alabama A&M University",
  "Alabama State University",
  "Alaska Pacific University",
  "Al Azhar University",
  "Albany College of Pharmacy and Health Sciences",
  "Albany State University",
  "Albertus Magnus College",
  "Albion College",
  "Albright College",
  "Alcorn State University",
  "Alderson Broaddus University",
  "Alexandria University",
  "Alexandru Ioan Cuza University",
  "Al-Farabi Kazakh National University",
  "Alfred University",
  "Alice Lloyd College",
  "Al-Imam Mohamed Ibn Saud Islamic University",
  "Allegheny College",
  "Allen College",
  "Allen University",
  "Alliant International University",
  "Alma College",
  "Alpen-Adria-Universität Klagenfurt",
  "Alvernia University",
  "Alverno College",
  "Amberton University",
  "American Academy of Art",
  "American Indian College of the Assemblies of God",
  "American InterContinental University",
  "American International College",
  "American Jewish University",
  "American Public University System",
  "American University",
  "American University in Bulgaria",
  "American University in Cairo",
  "American University of Beirut",
  "American University of Beirut (AUB)",
  "American University of Paris",
  "American University of Puerto Rico",
  "American University of Sharjah (AUS)",
  "Amherst College",
  "Amridge University",
  "Anderson University",
  "Andrews University",
  "Angelo State University",
  "Anna Maria College",
  "Antioch University",
  "Aoyama Gakuin University",
  "Appalachian Bible College",
  "Appalachian State University",
  "Aquinas College",
  "Arcadia University",
  "Argosy University",
  "Aristotle University of Thessaloniki",
  "Arizona Christian University",
  "Arizona State University",
  "Arizona State University - West",
  "Arkansas Baptist College",
  "Arkansas State University",
  "Arkansas Tech University",
  "Armstrong Atlantic State University",
  "Art Academy of Cincinnati",
  "Art Center College of Design",
  "Art Institute of Atlanta",
  "Art Institute of Colorado",
  "Art Institute of Houston",
  "Art Institute of Pittsburgh",
  "Art Institute of Portland",
  "Art Institute of Seattle",
  "Asbury University",
  "Ashford University",
  "Ashland University",
  "Assumption College",
  "Aston University",
  "Ateneo de Manila University",
  "Athens State University",
  "Athens University of Economy And Business",
  "Atlanta College of Arts"
];

/** What typing each of these into School returned on the live page. */
export const SCHOOL_SEARCHES: Record<string, string[]> = {
  "IIT": [
    "Indian Institute of Technology Bombay (IITB)",
    "Indian Institute of Technology Delhi (IITD)",
    "Indian Institute of Technology Guwahati (IITG)",
    "Indian Institute of Technology Kanpur (IITK)",
    "Indian Institute of Technology Kharagpur (IITKGP)",
    "Indian Institute of Technology Madras (IITM)",
    "Indian Institute of Technology Roorkee (IITR)"
  ],
  "Indian Institute of Technology": [
    "Indian Institute of Technology Bombay (IITB)",
    "Indian Institute of Technology Delhi (IITD)",
    "Indian Institute of Technology Guwahati (IITG)",
    "Indian Institute of Technology Kanpur (IITK)",
    "Indian Institute of Technology Kharagpur (IITKGP)",
    "Indian Institute of Technology Madras (IITM)",
    "Indian Institute of Technology Roorkee (IITR)"
  ],
  "Delhi": [
    "Indian Institute of Technology Delhi (IITD)",
    "SUNY College of Technology - Delhi",
    "University of Delhi"
  ],
  "Kharagpur": [
    "Indian Institute of Technology Kharagpur (IITKGP)"
  ],
  "Stanford": [
    "Stanford University"
  ],
  "BITS": [],
  "IIT Kharagpur": [],
  "IIT Delhi": [],
  "IIT Bombay": [],
  "University of Delhi": [
    "University of Delhi"
  ],
  "Delhi University": [],
  "Jadavpur": [],
  "Jadavpur University": [],
  "NIT": [
    "Eastern Mennonite University",
    "Granite State College",
    "South Seattle Community College",
    "Trinity Christian College",
    "Trinity College",
    "Trinity College Dublin",
    "Trinity College of Nursing & Health Sciences",
    "Trinity International University",
    "Trinity Lutheran College",
    "Trinity University",
    "Trinity Western University",
    "United Arab Emirates University",
    "United States Air Force Academy",
    "United States Coast Guard Academy",
    "United States International University - Kenya",
    "United States Merchant Marine Academy",
    "United States Military Academy",
    "United States Naval Academy",
    "United States Sports Academy",
    "Unity College",
    "University of Manitoba"
  ],
  "BITS Pilani": [],
  "Anna University": [
    "Susquehanna University"
  ],
  "University of Calcutta": [
    "University of Calcutta"
  ],
  "Manipal": []
};

/** What typing each of these into Location (City) returned. It shows nothing until you type. */
export const LOCATION_SEARCHES: Record<string, string[]> = {
  "Kolkata": [
    "Kolkata, West Bengal, India"
  ],
  "Bangalore": [
    "Bangalore, Karnataka, India",
    "Bangalore, Tamil Nadu, India",
    "Bangalore (East), Karnataka, India",
    "Bangalore (South), Karnataka, India",
    "Bangalore (North), Karnataka, India"
  ],
  "Bengaluru": [
    "Bengaluru, Karnataka, India"
  ],
  "Mumbai": [
    "Mumbai, Maharashtra, India",
    "Mumbai Suburban District, Maharashtra, India",
    "Navi Mumbai, Maharashtra, India",
    "Mumbaiwasti, Maharashtra, India",
    "Mumbaipada, Maharashtra, India",
    "Navi Mumbai, Maharashtra, India"
  ],
  "Delhi": [
    "Delhi, India",
    "New Delhi, Delhi, India",
    "Delhi Cantonment, Delhi, India",
    "Delhi, California, United States",
    "Delhi, Ontario, Canada",
    "Delhi Hills, Ohio, United States",
    "Delhi Hills, Ohio, United States",
    "Town of Delhi, New York, United States",
    "Delhi, Madhya Pradesh, India",
    "Delhi, New York, United States"
  ],
  "San Francisco": [
    "San Francisco, California, United States",
    "San Francisco de Macorís, Duarte, Dominican Republic",
    "San Francisco, Agusan del Sur, Philippines",
    "San Francisco De Borja, Lima, Peru",
    "San Francisco, Cebu, Philippines",
    "South San Francisco, California, United States"
  ],
  "New York": [
    "New York, New York, United States",
    "New Rochelle, New York, United States",
    "New City, New York, United States",
    "West New York, New Jersey, United States",
    "New Castle, New York, United States",
    "New Cassel, New York, United States",
    "Town of New Windsor, New York, United States",
    "New Square, New York, United States",
    "New Windsor, New York, United States"
  ],
  "Kolkata, India": [],
  "Hyderabad": [
    "Hyderabad, Andhra Pradesh, India",
    "Hyderabad, Sindh, Pakistan",
    "Hyderabad, Telangana, India",
    "Hyderabad Dona, Punjab, India",
    "Goth Hyderabad, Sindh, Pakistan",
    "Hyderabad, Punjab, Pakistan",
    "Chak Hyderabad, Punjab, Pakistan",
    "Hyderabad, Punjab, Pakistan",
    "Chak Hyderabad, Punjab, Pakistan",
    "Hyderabad, Sindh, Pakistan"
  ],
  "Pune": [
    "Pune, Maharashtra, India",
    "Punewadi, Maharashtra, India",
    "Punegaon, Maharashtra, India",
    "Punedahalli, Karnataka, India",
    "Punegaon, Maharashtra, India",
    "Punesra, Bihar, India",
    "Punegaon, Maharashtra, India",
    "Pune Purwa, Uttar Pradesh, India",
    "Punehari, Uttar Pradesh, India",
    "Punesa, West Bengal, India"
  ],
  "Chennai": [
    "Chennai, Tamil Nadu, India",
    "Gali Chennaiah Palem, Andhra Pradesh, India",
    "Chennaipally Tanda, Telangana, India",
    "Chennaikatte, Karnataka, India",
    "Chennaipalem, Telangana, India",
    "Chennaipally, Telangana, India",
    "Chennaithodi, Karnataka, India",
    "Chennaiahgunta, Andhra Pradesh, India",
    "Chennaiahgaripalle, Andhra Pradesh, India",
    "Chennaipally No-2, Telangana, India"
  ],
  "Gurgaon": [
    "Gurgaon, Bihar, India",
    "Gurgaon, Uttar Pradesh, India",
    "Gurgaon, Uttar Pradesh, India",
    "Gurgaon, Rajasthan, India",
    "Gurgaon, Uttar Pradesh, India",
    "Gurgaon, Uttar Pradesh, India",
    "Gurgaon, Uttar Pradesh, India",
    "Kundari Tao Gurgaon, Uttar Pradesh, India",
    "Gurgāon, Jharkhand, India",
    "Gurgaon, Uttar Pradesh, India"
  ],
  "Noida": [
    "Noida, Uttar Pradesh, India",
    "Greater Noida, Uttar Pradesh, India",
    "Noidans-lès-Vesoul, France",
    "Noidans-le-Ferroux, France",
    "Noidant-le-Rocheux, France",
    "Noidant-Chatenoy, France",
    "Noidan, France",
    "Noidanniemi, Finland"
  ]
};

export const DEGREES: string[] = [
  "Associate's Degree",
  "Bachelor's Degree",
  "Doctor of Medicine (M.D.)",
  "Doctor of Philosophy (Ph.D.)",
  "Engineer's Degree",
  "High School",
  "Juris Doctor (J.D.)",
  "Master of Business Administration (M.B.A.)",
  "Master's Degree",
  "Other"
];

export const DISCIPLINES: string[] = [
  "Accounting",
  "African Studies",
  "Agriculture",
  "Anthropology",
  "Applied Health Services",
  "Architecture",
  "Art",
  "Asian Studies",
  "Biology",
  "Business",
  "Business Administration",
  "Chemistry",
  "Classical Languages",
  "Communications & Film",
  "Computer Science",
  "Dentistry",
  "Developing Nations",
  "Discipline Unknown",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electronics",
  "Engineering",
  "English Studies",
  "Environmental Studies",
  "European Studies",
  "Fashion",
  "Finance",
  "Fine Arts",
  "General Studies",
  "Health Services",
  "History",
  "Humanities",
  "Human Resources Management",
  "Industrial Arts & Carpentry",
  "Information Systems",
  "International Relations",
  "Journalism",
  "Languages",
  "Latin American Studies",
  "Law",
  "Linguistics",
  "Manufacturing & Mechanics",
  "Mathematics",
  "Medicine",
  "Middle Eastern Studies",
  "Naval Science",
  "North American Studies",
  "Nuclear Technics",
  "Operations Research & Strategy",
  "Organizational Theory",
  "Other",
  "Philosophy",
  "Physical Education",
  "Physical Sciences",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Policy",
  "Public Service",
  "Religious Studies",
  "Russian & Soviet Studies",
  "Scandinavian Studies",
  "Science",
  "Slavic Studies",
  "Social Science",
  "Social Sciences",
  "Sociology",
  "Speech",
  "Statistics & Decision Theory",
  "Urban Studies",
  "Veterinary Medicine"
];

export const YES_NO: string[] = [
  "Yes",
  "No"
];

export const GENDER: string[] = [
  "Male",
  "Female",
  "I don't wish to answer"
];
export const RACE: string[] = [
  "American Indian or Alaska Native",
  "I don't wish to answer",
  "Asian",
  "Black or African American",
  "Hispanic or Latino",
  "Native Hawaiian or Other Pacific Islander",
  "Two or More Races",
  "White"
];
export const VETERAN: string[] = [
  "I am not a protected veteran",
  "I identify as one or more of the classifications of a protected veteran",
  "I don't wish to answer"
];
export const DISABILITY: string[] = [
  "Yes, I have a disability, or have had one in the past",
  "No, I do not have a disability and have not had one in the past",
  "I don't wish to answer"
];
export const GENDER_IDENTITY: string[] = [
  "Man",
  "Woman",
  "Non-binary or third gender",
  "Genderqueer",
  "I don't wish to answer"
];
export const RACE_OR_ETHNICITY: string[] = [
  "Black or of African descent",
  "East Asian",
  "Hispanic, Latine or of Spanish Origin",
  "Indigenous, American Indian or Alaska Native",
  "Middle Eastern or North African Native",
  "Hawaiian or Pacific Islander",
  "South Asian",
  "Southeast Asian",
  "White or European",
  "I don't wish to answer"
];
export const LGBTQ: string[] = [
  "Yes",
  "No",
  "I don't wish to answer"
];
